name: Linter

on:
  pull_request:
    branches:
      - main

jobs:
  linter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8==7.0.0
      
      - name: Run linter
        run: flake8 src/
      