name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  bazel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run bazel tests
        run: |
          bazel test //... || TEST_EXIT_CODE=$?
          if [ "${TEST_EXIT_CODE:-0}" != "0" ]
          then
            TEST_LOGS=$(bazel info bazel-testlogs)
            find $TEST_LOGS -name test.log -exec echo "Found log: {}" \; -exec cat {} \;
          fi
          exit ${TEST_EXIT_CODE:-0}
      